name: ${name}
version: ${version}
main: ${group}.${name}.MoreArmorsMain
api-version: 1.13
depend: [ProtocolLib]

commands:
  morearmors:
    description: MoreArmors Main Command
    aliases: [ma]
    usage: /command
  openplayerinventory:
    description: Testing
    aliases: [opi]
    usage: /command

permissions:
  morearmors.*:
    description: Gives access to all MoreArmors commands.
    children:
      morearmors.edit: true
      morearmors.give: true
      morearmors.reload: true
  morearmors.edit:
    description: Gives access to edit all MoreArmors items.
    default: op
  morearmors.give:
    description: Gives access to give all MoreArmors items.
    default: op
  morearmors.reload:
    description: Gives access to reloading MoreArmors.
    default: op